### ISSUE TITLE
How to add COM File?

### ISSUE THREAD

**Issue by Ibernato93** [ZeroPass/pymrtd#1]
Hi, 
How can I integrate a COM  and DG2 file read?

**Comment by smlu** [comment]
Hey, unfortunately parsing of files  EF.COM and EF.DG2 is not supported atm.
Currently supported files are: DF.DG1, DF.DG15, EF.SOD and partially DF.DG14.

**Comment by Ibernato93** [comment]
I have implemented reading the COM file. Then I'll make you the pull request.
 As regards the implementation of the dg2, dg11, dg12 files, if I create the classes in the same way as the other dgs, through the elementary class, could it work?

**Comment by smlu** [comment]
>I have implemented reading the COM file. Then I'll make you the pull request.

Awesome, thank you!

>I have implemented also DG11 but i get this error: ValueError: Extra data - 117 bytes of trailing data were provided
>
>Unfortunately in the absence of documentation it is difficult for me to understand how the whole process works. If you have time available, we can talk.

Fyi, underlying serialization is done by [asn1crypto](https://github.com/wbond/asn1crypto) library. The error you're getting is from lower layer of that library expecting fixed sized raw data with no padded data: [core.py:L1426-L1428](https://github.com/wbond/asn1crypto/blob/fad689f2072e405317436c8bf7f6609ba183a060/asn1crypto/core.py#L1426-L1428). You can override this behavior if you pass `strict=False` to the `asn1crypto` object when de-serializing.

**Comment by Ibernato93** [comment]
@smlu i pass False but the result is incorrect.
Can you please implements DG2? only the last tag (the image)
